### ISSUE TITLE
Customizing c-basic-offset doesn't appear to work

### ISSUE THREAD

**Issue by asppsa** [ejmr/php-mode#226]
Hello,

I was trying to set `c-basic-offset` under PHP to 2.  To do so, I tried `M-x customize-group<RET>C` and changed it in there.  Even after a restart of Emacs however, tab in a PHP file still produced four spaces.  In a C file, I got the expected 2 spaces.  The only way I could get around it was by adding a `php-mode-hook` that did a `(setq c-basic-offset 2)` ...

I'm using Emacs 24.4 and php-mode 1.15.3, installed from melpa-stable

**Comment by ejmr** [comment]
Sorry it's taken this many hours to see this issue and reply.  Could you please post the value of `php-mode-coding-style`?  My guess is it's going to be the default `PEAR`.  If it's anything but `Default` then what is happing is that PHP Mode is enabling one of the various c-mode styles that it defines, e.g. PEAR, PSR-2, Drupal, etc.  And they affect `c-basic-offset`.  And since PHP Mode is derived from CC Mode, when you customize the variable via `M-x customize-group <RET> C`, PHP Mode ends up overriding that anyway.

I am not justifying the behavior; I just think you deserve an explanation.  Thank you for raising this issue since I'm sure other users will run into it at some point, although I'm sorry it caused you an inconvenience.

**Comment by asppsa** [comment]
Hi there.  Firstly, no worries at all about the number of hours in responding!  I appreciate you taking the time to  look into this.

It looks like you have hit the nail on the head there.  I just checked and `php-coding-style` was set to `psr2`.  I have now changed it to `default` and tabbing works as expected now.  `default` seems fine, so this is solved as far as I am concerned!

Thanks again!
