### ISSUE TITLE
Drop Emacs 23 Support

### ISSUE THREAD

**Issue by ejmr** [ejmr/php-mode#247]
This would mainly involve updating the README.  See #214 for some discussion.  And please voice any disagreements with this decision here.

**Comment by andreas-roehler** [comment]
Don't see a need for an explicit drop.

Works well so far with 

GNU Emacs 23.4.1 (i686-pc-linux-gnu, GTK+ Version 2.24.21) of 2013-10-25 on akateko, modified by Debian

However, ert is broken and tests probably not worth  adapting to v23.

Maybe instead of announcing a drop telling "Tested against version XYZ"?

Avoiding lexical-binding should keep php-mode compatible.

**Comment by syohex** [comment]
IMO. I think it better to drop Emacs 23 support as maintainer. Supporting Emacs 23 makes maintenance hard. Recent platform(newer Linux distributions, MacOSX etc) cannot build Emacs 23(configure occurs error). We need to use Virtualbox or VMWare and old platforms for testing or fixing bug Emacs 23. It takes cost.

**Comment by ejmr** [comment]
The README stresses that PHP Mode requires Emacs 24 and while it *might* work with older versions, we will not be treating bugs related to older versions as priorities.  After a few months with that information I think we can safely close this issue now and move forward treating Emacs 24 as the baseline minimum.
