### ISSUE TITLE
Indentation of closures with `use` keyword is one level too deep if they are used as parameters

### ISSUE THREAD

**Issue by trashofmasters** [ejmr/php-mode#259]
This happens with Emacs 24 and 25 and various versions of php-mode, even the latest one.

To reproduce you can select and reindent this code and check it's indented as shown below:

```php
/**
 * This code shows how writing a closure which imports external
 * variables with the `use` keyword causes php-mode to incorrectly
 * indent one level deeper when the closure is used as the actual parameter
 * of another function.
 *
 * Expected indentation:
 *
 * $foo(function($par1, $par2) use ($ext) {
 *     return $par1 + $par2 + $ext;
 * });
 *
 * Actual indentation:
 *
 * $foo(function($par1, $par2) use ($ext) {
 *         return $par1 + $par2 + $ext;
 *     });
 */


// Indentation fails in the global scope.
$foo(function($par1, $par2) use ($ext) {
        return $par1 + $par2 + $ext;
    });

array_map(function($par1, $par2) use ($ext) {
        return $par1 + $par2 + $ext;
    }, $foo);


// Indentation fails in the method scope
class Foo
{
    protected function foo()
    {
        $foo(function($par1, $par2) use ($ext) {
                return $par1 + $par2 + $ext;
            });

        array_map(function($par1, $par2) use ($ext) {
                return $par1 + $par2 + $ext;
            }, $foo);
    }
}

// And also fails inside of a function scope
function foo() {
    $foo(function($par1, $par2) use ($ext) {
            return $par1 + $par2 + $ext;
        });

    array_map(function($par1, $par2) use ($ext) {
            return $par1 + $par2 + $ext;
        }, $foo);    
}
```

**Comment by ejmr** [comment]
If you use `C-c C-o` to change `defun-close` to `-` and `defun-block-intro` to `0` then we get the expected indentation in every scenario.  My gut says we can't solve this by setting those values for all situations, but instead might have to come up with an approach that applies those indentation values only when `use` is involved.

**Comment by trashofmasters** [comment]
I see where you are coming from. Somehow I remember the pain and frustration of getting c syntactic indentation to work under all possible circumstances.

I've found this answer on [Stackoverflow](http://stackoverflow.com/questions/11482667/how-to-fix-php-mode-indenting-when-using-closures) but I can't make it work properly, would you mind giving it a shot yourself?

```elisp
(defun unident-closure ()
  (let ((syntax (mapcar 'car c-syntactic-context)))
    (if (and (member 'arglist-cont-nonempty syntax)
             (or
              (member 'statement-block-intro syntax)
              (member 'brace-list-intro syntax)
              (member 'brace-list-close syntax)
              (member 'block-close syntax)))
        (save-excursion
          (beginning-of-line)
          (delete-char (* (count 'arglist-cont-nonempty syntax)
                          c-basic-offset))))))

(add-hook 'php-mode-hook (lambda ()
                           (add-hook 'c-special-indent-hook 'unident-closure))
```

It seems that [web-mode + flycheck](http://emacs.stackexchange.com/questions/12693/php-mode-indents-anonymous-function-incorrectly) can do the job, but in all honesty I would rather avoid using web-mode to author pure php files. 

I've never checked the code, but I strongly doubt that web-mode uses any indentation function from cc-mode.

```php
<?php
/**
 * Using web-mode and flycheck:
 * (flycheck-mode 1)
 * (flycheck-add-mode 'php 'web-mode)
 */

// Indentation fails in the global scope.
$foo(function($par1, $par2) use ($ext) {
    return $par1 + $par2 + $ext;
});

array_map(function($par1, $par2) use ($ext) {
    return $par1 + $par2 + $ext;
}, $foo);
```

**Comment by ejmr** [comment]
As-is `unindent-closure` did not work for me either, but thanks for posting it because that's a good starting point since, as I said, I expect we're going to have to implement a function specifically for handling this scenario.

> I've never checked the code, but I strongly doubt that web-mode uses any indentation function from cc-mode.

I don't think Web Mode does directly use anything from CC Mode.  If I remember correctly it often makes use of `indent-according-to-mode`, which makes perfect sense considering Web Mode deals with multiple languages.

**Comment by jwdunne** [comment]
Managed to get the hack working. The issue with the code above is that the symbols for intro and close in the syntax list are 'defun-block-intro and 'defun-close.

I haven't tried removing any of the other symbols - I have 0 experience with elisp so I'm currently a danger to my self and my editor. It might be good to keep for compatibility? Not sure. Hope this helps anyway.

```lisp
(defun unident-closure ()
  (let ((syntax (mapcar 'car c-syntactic-context)))
    (if (and (member 'arglist-cont-nonempty syntax)
             (or
              (member 'statement-block-intro syntax)
              (member 'brace-list-intro syntax)
              (member 'brace-list-close syntax)
              (member 'block-close syntax)
              (member 'defun-block-intro syntax)
              (member 'defun-close syntax)))
        (save-excursion
          (beginning-of-line)
          (delete-char (* (count 'arglist-cont-nonempty syntax)
                          c-basic-offset))))))
```

**Comment by ejmr** [comment]
Thank you for the contribution @jwdunne which I plan to test out today.

**Comment by ejmr** [comment]
So the version of `unindent-closure` provided by @jwdunne addresses all of the issues in the example @trashofmasters posted.  That said, I don't think we should use the code as-is.  I think it would be better to rewrite the function into something like `(defun php-unindent-closure (langelem) ...)` which would then be valid for use in `c-offset-alist`.

Alternatively, if we need to perform the calculation for many types of syntactical contexts---I'm not sure all those `(member ...)` tests are necessary---then we can consider making this logic part of `php-cautious-indent-line`.

Or simply rename the function to `php-unindent-closure` and add it to `c-special-indent-hook` as part of PHP Mode.  But this would be my least favorite approach since it would create a disparity between the implementation of what is effectively a lineup function (in CC Mode terms) and every other custom lineup function we use.

Thoughts?  Any good, obvious solution that I'm simply overlooking?

**Comment by jwdunne** [comment]
The problem I can see is that for functions without use, the symbol is correctly inlambda and so on, where as with the use it is seeing the start and end of the lambda as block level functions.

I have tried exploring how to correctly set the syntax symbol with the use keyword with php lambdas but I can't find anything definitive - I lack the experience so I'm not 100% sure if there's a simple fix that recognises PHP lambdas correctly.

Perhaps CC mode expects lexical or function scoping, where PHP has neither, so the use statement is an edge case unconsidered by CC mode.

The fact that the original unindent-closure was reportedly working but has since broken due to symbol name changes tells me that this hack isn't a permanent solution so it could break again with an external update.

**Comment by ejmr** [comment]
> I have tried exploring how to correctly set the syntax symbol with the `use` keyword with php lambdas... 

Good idea.  We can do this:

```lisp
(c-lang-defconst c-lambda-kwds php '("function" "use"))
```

After which closures with the `use` keyword will have the `inlambda` symbol in their syntactic context (you can use `C-c C-s` to see this).  So we could build from there by rewriting `php-unindent-closure` in such a way that we can add...

```
(inlambda . php-unindent-closure)
```

...to `c-offset-alist`.

**Comment by jwdunne** [comment]
Given that closures without use are indented correctly, would we still need to work in the hack?

The other problem I see is that use is also for aliasing namespaces and also traits. They've really put the k/we to good use...

**Comment by ejmr** [comment]
Would everyone please try out the (hopefully correct) fix in `unindent-closures` branch?  @syohex, I would also *greatly* appreciate it if you review the code before I merge it.

**Comment by syohex** [comment]
@ejmr Looks good. Great work :+1:.

**Comment by ejmr** [comment]
Thanks @syohex and everyone else.  I've merged the patch into `master`.
