### ISSUE TITLE
php-mode-test-dir not reliable

### ISSUE THREAD

**Issue by andreas-roehler** [ejmr/php-mode#267]
With 

https://github.com/ejmr/php-mode/commit/4b675b04638540e688ef9db436ce63c4ad4c651a

default-directory might be used to detect directory to run tests from.

default-directory is fairly volatile.

Why is such a guessing needed at all?

When running interactively, needed symbols are loaded and not further path required.
When running in batch-mode, provide path if neccessary.

**Comment by syohex** [comment]
If `php-mode-test-dir`is `"tests"`.

1. Open php-mode-test.el
2.  `M-x eval-buffer`
3. Open test file which is in tests/
4. Run test by `M-x ert-run-tests-interactively`

Then following error occurs.

```
F php-mode-test-issue-115
    Proper alignment for chained method calls inside arrays.
    (file-error "Opening input file" "no such file or directory" "/home/syohei/php-mode/tests/tests/issue-115.php")
```

**Comment by andreas-roehler** [comment]
Okay, see it. 

IMO there is no other way than hard-coding the path one way or the other.

Played with 

(file-name-directory (buffer-file-name (car (find-function-noselect 'php-mode))))

But that would fail, if another php-mode was loaded afterwards, then the tests dir might not be there.

What about sending the path from Makefile?

**Comment by ryuslash** [comment]
Have you had any actual issues with the commit you reference? Because I've seen and used that pattern before and I think that's basically *the* way to ensure you have the proper path.

As far as I know, when the file is loaded, interactively or not, `load-file-name` is filled and when a buffer is evaluated its `default-directory` is the directory in which that file is located. Am I missing something?

**Comment by andreas-roehler** [comment]
@ryuslash See report at #264 , eval-buffer fails at php-mode-test.el

**Comment by ryuslash** [comment]
From what I can tell, that's what was happening before 4b675b0
