### ISSUE TITLE
Config mode is chosen for Zend config files

### ISSUE THREAD

**Issue by sg2002** [ejmr/php-mode#367]
Zend framework often has config files with names that follow pattern "*.config.php". In auto-mode-alist there's this pattern ("[/.]c\\(?:on\\)?f\\(?:i?g\\)?\\(?:\\.[a-zA-Z0-9._-]+\\)?\\'" . conf-mode-maybe) - that selects conf-mode for them.
Since php-mode adds its patterns to the end of auto-mode-alist, the needed pattern just never fires. I see two options - add patterns to the front, but this may lead with compatibility problems with e. g. web-mode, or add patterns precisely just before the conf pattern.

**Comment by zonuexe** [comment]
This problem is same as #362.  I want to merge #363.

**Comment by sg2002** [comment]
I see. I searched through the open issues and couldn't find anything related.

**Comment by zonuexe** [comment]
@sg2002 
Your report was very valuable because both of these PRs have not yet been merged.
I recognized this problem for a long time, but the report was delayed. I'm sorry I bothered you. 🙇

**Comment by ejmr** [comment]
They are not yet merged because I felt it was necessary to make a few changes and that has taken longer than I planned.  Even though this seems like a trivial, simple bug to fix, please keep in mind that if I make a mistake and push out a bugged release then that affects *a lot* of people badly.  In the past I have rushed to push bug fixes only to find out it caused tons of new errors for all PHP Mode users who keep their version up to date.  So nowadays I am very cautious about certain merges.

@zonuexe I still intend to merge your branches, but it is taking me longer than I expected to tweak and test them thoroughly so that I am confident that I am not going to break PHP Mode when I do finally merge them.  I'm sorry about the delay though.

**Comment by zonuexe** [comment]
@ejmr 
I am afraid to destroy the environment of users, too.  I appreciate your consideration.

**Comment by ejmr** [comment]
Same, I appreciate your patience.
