### ISSUE TITLE
Font lock color for single quoted strings

### ISSUE THREAD

**Issue by bryan-kramer** [ejmr/php-mode#389]
The sudden switch to bright red for single quoted strings is unwelcome.

Is there some way to make single quoted strings look like double quoted strings?

![image](https://user-images.githubusercontent.com/3759834/32803314-1f338524-c951-11e7-9737-3e014da1819a.png)

It is also inconsistent - notice that the ```'false'``` is not colored bright red.

**Comment by MarTango** [comment]
I've also noticed that single-quotes often break the syntax highlighting in the whole document, and I have to get around it by replacing them with double quotes and then back to single quotes again.

**Comment by ahungry** [comment]
Yup, recent change has broken quotation highlighting if single quotes are used in the file, is anyone maintaining this package atm?

**Comment by ahungry** [comment]
Btw, it happens on a fresh load of a buffer - if you toggle out of php-mode into something like web-mode and then re-enable php-mode everything appears ok.

**Comment by ahungry** [comment]
Also if you just clone this repo and `(add-to-list 'load-path "/your/repo/dir")` the issue will go away, as there was a fix in commit 780f269 related to handling of C mode single quote java strings, so perhaps the ELPA installed version is hitting auto-load issues that the direct usage of the lib does not (and why maintainer may not have seen it).

**Comment by ejmr** [comment]
@ahungry

> ...is anyone maintaining this package atm?

Ostensibly @zonuexe is the maintainer, but the "transfer of power", so to speak, has been slow---and entirely because of me.  So the apparent lack of care or impetus to deal with bugs, yeah that fault lies solely with me, and for that I apologize.

@bryan-kramer 

If it is possible for you to post the file---or even just the specific part---where you are running into that problem, that will help us create a unit-test for this and/or strengthen existing ones.  If you can't, that is perfectly fine too.  There have been a number of times where users have been unable to provide such code for a variety of reasons, often legal, so if you can't then that's fine.

I assume you are using the latest version of PHP Mode though.  Please post that and the Emacs version info (via `C-h C-a`) to help us reproduce the problem.

@MarTango 

Are you using PHP Mode on files that contain a mixture of PHP and other languages like HTML or JavaScript?  Because in those situations...  You ever see any of the films in the *Terminator* franchise?  You know how there's always at least one scene of the future where an army of T-800s from SkyNet is stomping over the literal skulls of humanity?  That's what parsing for syntax highlighting is like when PHP Mode sees non-PHP languages: the T-800s start marching.

**Comment by MarTango** [comment]
@ejmr 

>Are you using PHP Mode on files that contain a mixture of PHP and other languages like HTML or JavaScript?
Nope. Just pure PHP files. I don't currently have any examples of code where it happens, and it's been at least a week since I've encountered it, but if I do encounter it again, I'll copy and paste the code / try to replicate it.

**Comment by ejmr** [comment]
@MarTango Thank you.  Based on the image by the OP, I assumed this issue was *probably* not some kind of PHP-and-HTML-error, but thanks for helping rule that out.

**Comment by zonuexe** [comment]
I'm sorry, I missed the report.  I am trying to solve it by reverting #385

**Comment by zonuexe** [comment]
@bryan-kramer @MarTango @ahungry @ejmr 
Due to these two reverts, the destruction of compatibility should have recovered.
(It has at least the same behavior as before October...)

I apologize for the inconvenience caused by my decision and response being late.

**Comment by ahungry** [comment]
Thanks all for looking into, appreciate your hard work!

**Comment by bryan-kramer** [comment]
Thanks.

**Comment by ahungry** [comment]
Btw, the problem code in Emacs causing this originally is, I believe, c-parse-quotes-after-change (just redefining the function to return nil prevents that mode from causing the problems with single quote / double quote distinctions).
