### ISSUE TITLE
Semantic imenu integration not working in GNU Emacs trunk

### ISSUE THREAD

**Issue by cjohansson** [ejmr/php-mode#419]
Hi!

If I open a `PHP` file containing functions or class methods I see them when I press `M-x imenu` in GNU Emacs `25.3` but when using GNU Emacs Trunk only some top variables are listed. Imenu works for other languages in GNU Emacs Trunk but not with `php-mode`.

I hope there is a fix for this.

**Comment by zonuexe** [comment]
@cjohansson Thank you for reporting.

**Comment by cjohansson** [comment]
Update, the problem only affects namespaces, classes and class methods. It doesn't affect functions

**Comment by fallchildren** [comment]
Could you provide a test file or a snippet which causes this? And could you provide the value of `imenu-create-index-function`?

**Comment by cjohansson** [comment]
Ok try this:

```php
<?php
namespace MyNameSpace;
class MyClass
{
    public function __construct() {}
    public function myFunctionA() {}
    public function myFunctionB() {}
}
```

I'm testing in `php-mode-20180219.1806` and `emacs-27.0.50.4`..

`M-x imenu` returns just a variable but `imenu-list` returns correctly.. But I have bound `imenu` to `helm-semantic-or-imenu`.. Trying to disable helm-semantic-or-imenu

Problem disappeared. It seems the problem is in fact related to `helm-semantic-or-imenu`. Does `helm-semantic-or-imenu` work for you in Emacs trunk?

**Comment by cjohansson** [comment]
Thanks for the help, I'm closing this issue since it doesn't seem to be caused by php-mode, it seems to be related to helm

**Comment by fallchildren** [comment]
Just tried it with `helm-semantic-or-imenu`. The problem seems to be that it tries to use the semantic stuff and not the proper imenu functions. Semantic is not really implemented for `php-mode` so you get incomplete results. If you turn off semantic-mode you should see other results. The root of the problem is "again" that `php-mode` derives from `c-mode` and semantic support is enabled for `c-mode` so for `php-mode` also. So this is more or less still a problem in `php-mode` and not in `helm-semantic-or-imenu`.  If you're interested see issue: #407 which is another issue because of this. There is ongoing work in pull request: #409 for the root of the problem :)

**Comment by cjohansson** [comment]
Ah I see, thanks for explaining. I'll check out the other related issues
