### ISSUE TITLE
Opening tag has wrong colour

### ISSUE THREAD

**Issue by forthrin** [ejmr/php-mode#443]
The open/close short tags `<?>` and `?>` are coloured correctly, while the recommended opening tag `<?php` is not. I tried adding `<?php` to the regexp list as a shot in the dark, but the colour is still wrong.

On a side note, it seems a bit peculiar to let the PHP tag inherit the colour of the not-very-related constant face, but maybe it was the least unrelated choice?

```
(defface php-php-tag '((t (:inherit font-lock-constant-face)))
  "PHP Mode face used to highlight PHP tags."
  :group 'php-faces)

(...)

     ;; While c-opt-cpp-* highlights the <?php opening tags, it is not
     ;; possible to make it highlight short open tags and closing tags
     ;; as well. So we force the correct face on all cases that
     ;; c-opt-cpp-* lacks for this purpose.
     ;;
     ;; Note that starting a file with <% breaks indentation, a
     ;; limitation we can/should live with.
     (,(regexp-opt '("?>" "<?" "<%" "%>")) 0 'php-php-tag)))
  "Detailed highlighting for PHP Mode.")
```

**Comment by ejmr** [comment]
When browsing GitHub I still read all the notifications about this project.  I tend to stay out of it since @zonuexe has been doing a fantastic job as the maintainer.  But in this specific case I happen to know the reason for this:

> On a side note, it seems a bit peculiar to let the PHP tag inherit the colour of the not-very-related constant face, but maybe it was the least unrelated choice?

The tag uses `font-lock-constant-face` because it is, for all intents and purposes, constant.  That was my train of the thought at the time, anyway.

I should also point out a weird caveat with `<?php` which will affect any attempts to use regular expressions to fontify it: the tag *requires* whitespace after it.  For example, this code is correct:

```php
<?php /* Foo */ echo "Bar"; ?>
```

This code, however, will not work:

```php
<?php/* Foo */ echo "Bar"; ?>
```

**Comment by zonuexe** [comment]
I worked on the problem looking at this problem this morning, but it has not yet been completely solved.  Please wait for a while.  (And now I am working in a Japanese office and now is an afternoon)

**Comment by zonuexe** [comment]
@forthrin @ejmr 

This issue is resolved by #445. 
We got a beautiful coloring of tags.  Thank you for reporting!

<img width="601" alt="2018-03-23 8 56 56" src="https://user-images.githubusercontent.com/822086/37828533-f8ede80c-2ede-11e8-9a7a-7291b259aa18.png">

**Comment by forthrin** [comment]
@zonuexe: Beautiful! One less annoyance in the world :) When will the new release show up on MELPA?

**Comment by zonuexe** [comment]
@forthrin MELPA builds to the latest status once every few hours. If you are using MELPA (not stable), you can get it in a latest version about 2 hours later.

**Comment by forthrin** [comment]
@zonuexe: Using 20180323.512, `<?`, `?>` and `<?php` all have the same colour, inherited from `font-lock-preprocessor-face`. This is a perfect solution!
